import tkinter as tk






container_list = ["self.root,", "self.frm,", "self.frm1," "self.frm2,", "self.frm3,", "top,"]
fontlist = [
    "@Arial Unicode MS",
    "@MS Gothic",
    "@MS PGothic",
    "@MS UI Gothic",
    "@Malgun Gothic",
    "@Malgun Gothic Semilight",
    "@Microsoft JhengHei",
    "@Microsoft JhengHei Light",
    "@Microsoft JhengHei UI",
    "@Microsoft JhengHei UI Light",
    "@Microsoft YaHei",
    "@Microsoft YaHei Light",
    "@Microsoft YaHei UI",
    "@Microsoft YaHei UI Light",
    "@MingLiU-ExtB",
    "@MingLiU_HKSCS-ExtB",
    "@NSimSun",
    "@PMingLiU-ExtB",
    "@SimSun",
    "@SimSun-ExtB",
    "@Yu Gothic",
    "@Yu Gothic Light",
    "@Yu Gothic Medium",
    "@Yu Gothic UI",
    "@Yu Gothic UI Light",
    "@Yu Gothic UI Semibold",
    "@Yu Gothic UI Semilight",
    "Agency FB",
    "Algerian",
    "Arabic Transparent",
    "Arial",
    "Arial Baltic",
    "Arial Black",
    "Arial CE",
    "Arial CYR",
    "Arial Greek",
    "Arial Narrow",
    "Arial Rounded MT Bold",
    "Arial TUR",
    "Arial Unicode MS",
    "Bahnschrift",
    "Bahnschrift Condensed",
    "Bahnschrift Light",
    "Bahnschrift Light Condensed",
    "Bahnschrift Light SemiCondensed",
    "Bahnschrift SemiBold",
    "Bahnschrift SemiBold Condensed",
    "Bahnschrift SemiBold SemiConden",
    "Bahnschrift SemiCondensed",
    "Bahnschrift SemiLight",
    "Bahnschrift SemiLight Condensed",
    "Bahnschrift SemiLight SemiConde",
    "Baskerville Old Face",
    "Bauhaus 93",
    "Bell MT",
    "Berlin Sans FB",
    "Berlin Sans FB Demi",
    "Bernard MT Condensed",
    "Blackadder ITC",
    "Bodoni MT",
    "Bodoni MT Black",
    "Bodoni MT Condensed",
    "Bodoni MT Poster Compressed",
    "Book Antiqua",
    "Bookman Old Style",
    "Bookshelf Symbol 7",
    "Bradley Hand ITC",
    "Britannic Bold",
    "Broadway",
    "Brush Script MT",
    "Calibri",
    "Calibri Light",
    "Californian FB",
    "Caself.listo MT",
    "Cambria",
    "Cambria Math",
    "Candara",
    "Candara Light",
    "Castellar",
    "Centaur",
    "Century",
    "Century Gothic",
    "Century Schoolbook",
    "Chiller",
    "Colonna MT",
    "Comic Sans MS",
    "Consolas",
    "Constantia",
    "Cooper Black",
    "Copperplate Gothic Bold",
    "Copperplate Gothic Light",
    "Coself.rbel",
    "Coself.rbel Light",
    "Courier",
    "Courier New",
    "Courier New Baltic",
    "Courier New CE",
    "Courier New CYR",
    "Courier New Greek",
    "Courier New TUR",
    "Curlz MT",
    "Dubai",
    "Dubai Light",
    "Dubai Medium",
    "Ebrima",
    "Edwardian Script ITC",
    "Elephant",
    "Engravers MT",
    "Eras Bold ITC",
    "Eras Demi ITC",
    "Eras Light ITC",
    "Eras Medium ITC",
    "Felix Titling",
    "Fixedsys",
    "Footlight MT Light",
    "Forte",
    "Franklin Gothic Book",
    "Franklin Gothic Demi",
    "Franklin Gothic Demi Cond",
    "Franklin Gothic Heavy",
    "Franklin Gothic Medium",
    "Franklin Gothic Medium Cond",
    "Freestyle Script",
    "French Script MT",
    "Gabriola",
    "Gadugi",
    "Garamond",
    "Georgia",
    "Gigi",
    "Gill Sans MT",
    "Gill Sans MT Condensed",
    "Gill Sans MT Ext Condensed Bold",
    "Gill Sans Ultra Bold",
    "Gill Sans Ultra Bold Condensed",
    "Gloucester MT Extra Condensed",
    "Goudy Old Style",
    "Goudy Stout",
    "Haettenschweiler",
    "Harlow Solid Italic",
    "Harrington",
    "High Tower self.text",
    "HoloLens MDL2 Assets",
    "Impact",
    "Imprint MT Shadow",
    "Informal Roman",
    "Ink Free",
    "Javanese self.text",
    "Jokerman",
    "Juice ITC",
    "Kristen ITC",
    "Kunstler Script",
    "Leelawadee UI",
    "Leelawadee UI Semilight",
    "Lucida Bright",
    "Lucida Calligraphy",
    "Lucida Console",
    "Lucida Fax",
    "Lucida Handwriting",
    "Lucida Sans",
    "Lucida Sans Typewriter",
    "Lucida Sans Unicode",
    "MS Gothic",
    "MS Outlook",
    "MS PGothic",
    "MS Reference Sans Serif",
    "MS Reference Specialty",
    "MS Sans Serif",
    "MS Serif",
    "MS UI Gothic",
    "MV Boli",
    "Magneto",
    "Maiandra GD",
    "Malgun Gothic",
    "Malgun Gothic Semilight",
    "Marlett",
    "Matura MT Script Capitals",
    "Microsoft Himalaya",
    "Microsoft JhengHei",
    "Microsoft JhengHei Light",
    "Microsoft JhengHei UI",
    "Microsoft JhengHei UI Light",
    "Microsoft New Tai Lue",
    "Microsoft PhagsPa",
    "Microsoft Sans Serif",
    "Microsoft Tai Le",
    "Microsoft YaHei",
    "Microsoft YaHei Light",
    "Microsoft YaHei UI",
    "Microsoft YaHei UI Light",
    "Microsoft Yi Baiti",
    "MingLiU-ExtB",
    "MingLiU_HKSCS-ExtB",
    "Mistral",
    "Modern",
    "Modern No. 20",
    "Mongolian Baiti",
    "Monotype Corsiva",
    "Myanmar self.text",
    "NSimSun",
    "Niagara Engraved",
    "Niagara Solid",
    "Nirmala UI",
    "Nirmala UI Semilight",
    "OCR A Extended",
    "Old English self.text MT",
    "Onyx",
    "PMingLiU-ExtB",
    "Palace Script MT",
    "Palatino Linotype",
    "Papyrus",
    "Parchment",
    "Perpetua",
    "Perpetua Titling MT",
    "Playbill",
    "Poor Richard",
    "Pristina",
    "Rage Italic",
    "Ravie",
    "Rockwell",
    "Rockwell Condensed",
    "Rockwell Extra Bold",
    "Roman",
    "Script",
    "Script MT Bold",
    "Segoe MDL2 Assets",
    "Segoe Print",
    "Segoe Script",
    "Segoe UI",
    "Segoe UI Black",
    "Segoe UI Emoji",
    "Segoe UI Historic",
    "Segoe UI Light",
    "Segoe UI Semibold",
    "Segoe UI Semilight",
    "Segoe UI Symbol",
    "Showcard Gothic",
    "SimSun",
    "SimSun-ExtB",
    "Sitka Banner",
    "Sitka Display",
    "Sitka Heading",
    "Sitka Small",
    "Sitka Subheading",
    "Sitka self.text",
    "Small Fonts",
    "Snap ITC",
    "Stencil",
    "Sylfaen",
    "Symbol",
    "System",
    "Tahoma",
    "Tempus Sans ITC",
    "Terminal",
    "Times New Roman",
    "Times New Roman Baltic",
    "Times New Roman CE",
    "Times New Roman CYR",
    "Times New Roman Greek",
    "Times New Roman TUR",
    "Trebuchet MS",
    "Tw Cen MT",
    "Tw Cen MT Condensed",
    "Tw Cen MT Condensed Extra Bold",
    "Univers LT Std 45 Light",
    "Univers LT Std 47 Cn Lt",
    "Univers LT Std 55",
    "Univers LT Std 57 Cn",
    "Verdana",
    "Viner Hand ITC",
    "Vivaldi",
    "Vladimir Script",
    "Webdings",
    "Wide Latin",
    "Wingdings",
    "Wingdings 2",
    "Wingdings 3",
    "Yu Gothic",
    "Yu Gothic Light",
    "Yu Gothic Medium",
    "Yu Gothic UI",
    "Yu Gothic UI Light",
    "Yu Gothic UI Semibold",
    "Yu Gothic UI Semilight",
    "URW Chancery L",
]


def widgetname(self):
    s1 = self.cb.get()
    s2 = sp1.get()
    widget = s1 + s2
    var1 = e1.get()
    var2 = e2.get()
    var3 = sp2.get()
    var4 = sp3.get()
    punct1 = ")"
    geo_str = ".grid("
    txt6 = geo_str + "row=" + sp5.get(), "column=" + sp6.get() + punct1

    wstr = widget + var1 + var2 + "height=" + var3 + "," + "width=" + var4
    lb.insert(1, wstr)

    final_str = wstr + txt6
    self.text2.insert("1.0.", final_str)


colors_list = [
    "snow",
    "ghost white",
    "white smoke",
    "gainsboro",
    "floral white",
    "old lace",
    "linen",
    "antique white",
    "papaya whip",
    "blanched almond",
    "bisque",
    "peach puff",
    "navajo white",
    "lemon chiffon",
    "mint cream",
    "azure",
    "alice blue",
    "lavender",
    "lavender blush",
    "misty rose",
    "dark slate gray",
    "dim gray",
    "slate gray",
    "light slate gray",
    "gray",
    "light gray",
    "midnight blue",
    "navy",
    "cornflower blue",
    "dark slate blue",
    "slate blue",
    "medium slate blue",
    "light slate blue",
    "medium blue",
    "royal blue",
    "blue",
    "dodger blue",
    "deep sky blue",
    "sky blue",
    "light sky blue",
    "steel blue",
    "light steel blue",
    "light blue",
    "powder blue",
    "pale turquoise",
    "dark turquoise",
    "medium turquoise",
    "turquoise",
    "cyan",
    "light cyan",
    "cadet blue",
    "medium aquamarine",
    "aquamarine",
    "dark green",
    "dark olive green",
    "dark sea green",
    "sea green",
    "medium sea green",
    "light sea green",
    "pale green",
    "spring green",
    "lawn green",
    "medium spring green",
    "green yellow",
    "lime green",
    "yellow green",
    "forest green",
    "olive drab",
    "dark khaki",
    "khaki",
    "pale goldenrod",
    "light goldenrod yellow",
    "light yellow",
    "yellow",
    "gold",
    "light goldenrod",
    "goldenrod",
    "dark goldenrod",
    "rosy brown",
    "indian red",
    "saddle brown",
    "sandy brown",
    "dark salmon",
    "salmon",
    "light salmon",
    "orange",
    "dark orange",
    "coral",
    "light coral",
    "tomato",
    "orange red",
    "red",
    "hot pink",
    "deep pink",
    "pink",
    "light pink",
    "pale violet red",
    "maroon",
    "medium violet red",
    "violet red",
    "medium orchid",
    "dark orchid",
    "dark violet",
    "blue violet",
    "purple",
    "medium purple",
    "thistle",
    "snow2",
    "snow3",
    "snow4",
    "seashell2",
    "seashell3",
    "seashell4",
    "AntiqueWhite1",
    "AntiqueWhite2",
    "AntiqueWhite3",
    "AntiqueWhite4",
    "bisque2",
    "bisque3",
    "bisque4",
    "PeachPuff2",
    "PeachPuff3",
    "PeachPuff4",
    "NavajoWhite2",
    "NavajoWhite3",
    "NavajoWhite4",
    "LemonChiffon2",
    "LemonChiffon3",
    "LemonChiffon4",
    "cornsilk2",
    "cornsilk3",
    "cornsilk4",
    "ivory2",
    "ivory3",
    "ivory4",
    "honeydew2",
    "honeydew3",
    "honeydew4",
    "Lavendeself.rblush2",
    "Lavendeself.rblush3",
    "Lavendeself.rblush4",
    "MistyRose2",
    "MistyRose3",
    "MistyRose4",
    "azure2",
    "azure3",
    "azure4",
    "SlateBlue1",
    "SlateBlue2",
    "SlateBlue3",
    "SlateBlue4",
    "RoyalBlue1",
    "RoyalBlue2",
    "RoyalBlue3",
    "RoyalBlue4",
    "blue2",
    "blue4",
    "Dodgeself.rblue2",
    "Dodgeself.rblue3",
    "Dodgeself.rblue4",
    "SteelBlue1",
    "SteelBlue2",
    "SteelBlue3",
    "SteelBlue4",
    "DeepSkyBlue2",
    "DeepSkyBlue3",
    "DeepSkyBlue4",
    "SkyBlue1",
    "SkyBlue2",
    "SkyBlue3",
    "SkyBlue4",
    "LightSkyBlue1",
    "LightSkyBlue2",
    "LightSkyBlue3",
    "LightSkyBlue4",
    "Slategray1",
    "Slategray2",
    "Slategray3",
    "Slategray4",
    "LightSteelBlue1",
    "LightSteelBlue2",
    "LightSteelBlue3",
    "LightSteelBlue4",
    "LightBlue1",
    "LightBlue2",
    "LightBlue3",
    "LightBlue4",
    "LightCyan2",
    "LightCyan3",
    "LightCyan4",
    "PaleTurquoise1",
    "PaleTurquoise2",
    "PaleTurquoise3",
    "PaleTurquoise4",
    "CadetBlue1",
    "CadetBlue2",
    "CadetBlue3",
    "CadetBlue4",
    "turquoise1",
    "turquoise2",
    "turquoise3",
    "turquoise4",
    "cyan2",
    "cyan3",
    "cyan4",
    "DarkSlategray1",
    "DarkSlategray2",
    "DarkSlategray3",
    "DarkSlategray4",
    "aquamarine2",
    "aquamarine4",
    "DarkSeaGreen1",
    "DarkSeaGreen2",
    "DarkSeaGreen3",
    "DarkSeaGreen4",
    "SeaGreen1",
    "SeaGreen2",
    "SeaGreen3",
    "PaleGreen1",
    "PaleGreen2",
    "PaleGreen3",
    "PaleGreen4",
    "SpringGreen2",
    "SpringGreen3",
    "SpringGreen4",
    "green2",
    "green3",
    "green4",
    "chartreuse2",
    "chartreuse3",
    "chartreuse4",
    "OliveDrab1",
    "OliveDrab2",
    "OliveDrab4",
    "DarkOliveGreen1",
    "DarkOliveGreen2",
    "DarkOliveGreen3",
    "DarkOliveGreen4",
    "khaki1",
    "khaki2",
    "khaki3",
    "khaki4",
    "LightGoldenrod1",
    "LightGoldenrod2",
    "LightGoldenrod3",
    "LightGoldenrod4",
    "LightYellow2",
    "LightYellow3",
    "LightYellow4",
    "yellow2",
    "yellow3",
    "yellow4",
    "gold2",
    "gold3",
    "gold4",
    "goldenrod1",
    "goldenrod2",
    "goldenrod3",
    "goldenrod4",
    "DarkGoldenrod1",
    "DarkGoldenrod2",
    "DarkGoldenrod3",
    "DarkGoldenrod4",
    "RosyBrown1",
    "RosyBrown2",
    "RosyBrown3",
    "RosyBrown4",
    "IndianRed1",
    "IndianRed2",
    "IndianRed3",
    "IndianRed4",
    "sienna1",
    "sienna2",
    "sienna3",
    "sienna4",
    "burlywood1",
    "burlywood2",
    "burlywood3",
    "burlywood4",
    "wheat1",
    "wheat2",
    "wheat3",
    "wheat4",
    "tan1",
    "tan2",
    "tan4",
    "chocolate1",
    "chocolate2",
    "chocolate3",
    "firebrick1",
    "firebrick2",
    "firebrick3",
    "firebrick4",
    "brown1",
    "brown2",
    "brown3",
    "brown4",
    "salmon1",
    "salmon2",
    "salmon3",
    "salmon4",
    "LightSalmon2",
    "LightSalmon3",
    "LightSalmon4",
    "orange2",
    "orange3",
    "orange4",
    "DarkOrange1",
    "DarkOrange2",
    "DarkOrange3",
    "DarkOrange4",
    "coral1",
    "coral2",
    "coral3",
    "coral4",
    "tomato2",
    "tomato3",
    "tomato4",
    "OrangeRed2",
    "OrangeRed3",
    "OrangeRed4",
    "red2",
    "red3",
    "red4",
    "DeepPink2",
    "DeepPink3",
    "DeepPink4",
    "HotPink1",
    "HotPink2",
    "HotPink3",
    "HotPink4",
    "pink1",
    "pink2",
    "pink3",
    "pink4",
    "LightPink1",
    "LightPink2",
    "LightPink3",
    "LightPink4",
    "PaleVioletRed1",
    "PaleVioletRed2",
    "PaleVioletRed3",
    "PaleVioletRed4",
    "maroon1",
    "maroon2",
    "maroon3",
    "maroon4",
    "VioletRed1",
    "VioletRed2",
    "VioletRed3",
    "VioletRed4",
    "magenta2",
    "magenta3",
    "magenta4",
    "orchid1",
    "orchid2",
    "orchid3",
    "orchid4",
    "plum1",
    "plum2",
    "plum3",
    "plum4",
    "MediumOrchid1",
    "MediumOrchid2",
    "MediumOrchid3",
    "MediumOrchid4",
    "DarkOrchid1",
    "DarkOrchid2",
    "DarkOrchid3",
    "DarkOrchid4",
    "purple1",
    "purple2",
    "purple3",
    "purple4",
    "MediumPurple1",
    "MediumPurple2",
    "MediumPurple3",
    "MediumPurple4",
    "thistle1",
    "thistle2",
    "thistle3",
    "thistle4",
    "grey1",
    "grey2",
    "grey3",
    "grey4",
    "grey5",
    "grey6",
    "grey7",
    "grey8",
    "grey9",
    "grey10",
    "grey11",
    "grey12",
    "grey13",
    "grey14",
    "grey15",
    "grey16",
    "grey17",
    "grey18",
    "grey19",
    "grey20",
    "grey21",
    "grey22",
    "grey23",
    "grey24",
    "grey25",
    "grey26",
    "grey27",
    "grey28",
    "grey29",
    "grey30",
    "grey31",
    "grey32",
    "grey33",
    "grey34",
    "grey35",
    "grey36",
    "grey37",
    "grey38",
    "grey39",
    "grey40",
    "grey42",
    "grey43",
    "grey44",
    "grey45",
    "grey46",
    "grey47",
    "grey48",
    "grey49",
    "grey50",
    "grey51",
    "grey52",
    "grey53",
    "grey54",
    "grey55",
    "grey56",
    "grey57",
    "grey58",
    "grey59",
    "grey60",
    "grey61",
    "grey62",
    "grey63",
    "grey64",
    "grey65",
    "grey66",
    "grey67",
    "grey68",
    "grey69",
    "grey70",
    "grey71",
    "grey72",
    "grey73",
    "grey74",
    "grey75",
    "grey76",
    "grey77",
    "grey78",
    "grey79",
    "grey80",
    "grey81",
    "grey82",
    "grey83",
    "grey84",
    "grey85",
    "grey86",
    "grey87",
    "grey88",
    "grey89",
    "grey90",
    "grey91",
    "grey92",
    "grey93",
    "grey94",
    "grey95",
    "grey97",
    "grey98",
    "grey99",
]


punct_list = ["(", ")", "<", ">", "<<", ">>", "_", "__", ",", ":", ";", "+", "*", "."]
gridlist = [
    ".grid(row=1, column=1)",
    ".grid(row=2, column=1)",
    ".grid(row=3, column=1)",
    ".grid(row=4, column=1)",
    ".grid(row=5, column=1)",
    ".grid(row=6, column=1)",
    ".grid(row=7, column=1)",
    ".grid(row=8, column=1)",
    ".grid(row=9, column=1)",
    ".grid(row=1, column=2)",
    ".grid(row=2, column=2)",
    ".grid(row=3, column=2)",
    ".grid(row=4, column=2)",
    ".grid(row=5, column=2)",
    ".grid(row=6, column=2)",
    ".grid(row=7, column=2)",
    ".grid(row=8, column=2)",
    ".grid(row=9, column=2)",
    ".grid(row=1, column=3)",
    ".grid(row=2, column=3)",
    ".grid(row=3, column=3)",
    ".grid(row=4, column=3)",
    ".grid(row=5, column=3)",
    ".grid(row=6, column=3)",
    ".grid(row=7, column=3)",
    ".grid(row=8, column=3)",
    ".grid(row=9, column=3)",
    ".grid(row=1, column=2)",
    ".grid(row=2, column=2)",
    ".grid(row=3, column=2)",
    ".grid(row=4, column=2)",
    ".grid(row=5, column=2)",
    ".grid(row=6, column=2)",
    ".grid(row=7, column=2)",
    ".grid(row=8, column=3)",
    ".grid(row=9, column=3)",
    ".grid(row=4, column=3)",
    ".grid(row=5, column=3)",
    ".grid(row=6, column=3)",
    ".grid(row=7, column=3)",
    ".grid(row=8, column=3)",
    ".grid(row=9, column=3)",
    ".grid(row=0, column=4)",
    ".grid(row=1, column=4)",
    ".grid(row=2, column=4)",
    ".grid(row=3, column=4)",
    ".grid(row=4, column=4)",
    ".grid(row=5, column=4)",
    ".grid(row=6, column=4)",
    ".grid(row=7, column=4)",
    ".grid(row=8, column=4)",
    ".grid(row=9, column=4)",
    ".grid(row=0, column=5)"
    ".grid(row=0, column=1)",
    ".grid(row=0, column=2)",
    ".grid(row=0, column=3)",
    ".grid(row=0, column=4)",
    ".grid(row=0, column=5)",
    ".grid(row=0, column=6)",
    ".grid(row=0, column=7)",
    ".grid(row=0, column=8)",
    ".grid(row=0, column=9)",
    ".grid(row=1, column=1)",
    ".grid(row=1, column=2)",
    ".grid(row=1, column=3)",
    ".grid(row=1, column=4)",
    ".grid(row=1, column=5)",
    ".grid(row=1, column=6)",
    ".grid(row=1, column=7)",
    ".grid(row=1, column=8)",
    ".grid(row=1, column=9)",
    ".grid(row=2, column=0)",
    ".grid(row=2, column=1)",
    ".grid(row=2, column=2)",
    ".grid(row=2, column=3)",
    ".grid(row=2, column=4)",
    ".grid(row=2, column=5)",
    ".grid(row=2, column=6)",
    ".grid(row=2, column=7)",
    ".grid(row=2, column=8)",
    ".grid(row=2, column=9)",
    ".grid(row=3, column=0)",
    ".grid(row=3, column=1)",
    ".grid(row=3, column=2)",
    ".grid(row=3, column=3)",
    ".grid(row=3, column=4)",
    ".grid(row=3, column=5)",
    ".grid(row=3, column=6)",
    ".grid(row=3, column=7)",
    ".grid(row=3, column=8)",
    ".grid(row=3, column=9)",
    ".grid(row=4, column=0)",
    ".grid(row=4, column=1)",
    ".grid(row=4, column=2)",
    ".grid(row=4, column=3)",
    ".grid(row=4, column=4)",
    ".grid(row=4, column=5)",
    ".grid(row=4, column=6)",
    ".grid(row=4, column=7)",
    ".grid(row=4, column=8)",
    ".grid(row=4, column=9)",
    ".grid(row=1, column=5)",
    ".grid(row=2, column=5)",
    ".grid(row=3, column=5)",
    ".grid(row=4, column=5)",
    ".grid(row=5, column=5)",
    ".grid(row=6, column=5)",
    ".grid(row=7, column=5)",
    ".grid(row=8, column=5)",
    ".grid(row=9, column=5)",
    ".grid(row=10, column=5)",
    ".grid(row=1, column=6)",
    ".grid(row=2, column=6)",
    ".grid(row=3, column=6)",
    ".grid(row=4, column=6)",
    ".grid(row=5, column=6)",
    ".grid(row=6, column=6)",
    ".grid(row=7, column=6)",
    ".grid(row=8, column=6)",
    ".grid(row=9, column=5)",
    ".grid(row=0, column=5)",
    ".grid(row=6, column=6)",
    ".grid(row=7, column=7)",
    ".grid(row=8, column=8)",
    ".grid(row=9, column=9)",
    ".grid(row=1, column=7)",
    ".grid(row=7, column=1)",
]


font list2 = [
    "@Arial Unicode MS",
    "@MS Gothic",
    "@MS PGothic",
    "@MS UI Gothic",
    "@Malgun Gothic",
    "@Malgun Gothic Semilight",
    "@Microsoft JhengHei",
    "@Microsoft JhengHei Light",
    "@Microsoft JhengHei UI",
    "@Microsoft JhengHei UI Light",
    "@Microsoft YaHei",
    "@Microsoft YaHei Light",
    "@Microsoft YaHei UI",
    "@Microsoft YaHei UI Light",
    "@MingLiU-ExtB",
    "@MingLiU_HKSCS-ExtB",
    "@NSimSun",
    "@PMingLiU-ExtB",
    "@SimSun",
    "@SimSun-ExtB",
    "@Yu Gothic",
    "@Yu Gothic Light",
    "@Yu Gothic Medium",
    "@Yu Gothic UI",
    "@Yu Gothic UI Light",
    "@Yu Gothic UI Semibold",
    "@Yu Gothic UI Semilight",
    "Agency FB",
    "Algerian",
    "Arabic Transparent",
    "Arial",
    "Arial Baltic",
    "Arial Black",
    "Arial CE",
    "Arial CYR",
    "Arial Greek",
    "Arial Narrow",
    "Arial Rounded MT Bold",
    "Arial TUR",
    "Arial Unicode MS",
    "Bahnschrift",
    "Bahnschrift Condensed",
    "Bahnschrift Light",
    "Bahnschrift Light Condensed",
    "Bahnschrift Light SemiCondensed",
    "Bahnschrift SemiBold",Cut
    "Bahnschrift SemiBold Condensed",
    "Bahnschrift SemiBold SemiConden",
    "Bahnschrift SemiCondensed",
    "Bahnschrift SemiLight",
    "Bahnschrift SemiLight Condensed",
    "Bahnschrift SemiLight SemiConde",
    "Baskerville Old Face",
    "Bauhaus 93",
    "Bell MT",
    "Berlin Sans FB",
    "Berlin Sans FB Demi",
    "Bernard MT Condensed",
    "Blackadder ITC",
    "Bodoni MT",
    "Bodoni MT Black",
    "Bodoni MT Condensed",
    "Bodoni MT Poster Compressed",
    "Book Antiqua",
    "Bookman Old Style",
    "Bookshelf Symbol 7",
    "Bradley Hand ITC",
    "Britannic Bold",
    "Broadway",
    "Brush Script MT",
    "Calibri",
    "Calibri Light",
    "Californian FB",
    "Caself.listo MT",
    "Cambria",
    "Cambria Math",
    "Candara",
    "Candara Light",
    "Castellar",
    "Centaur",
    "Century",
    "Century Gothic",
    "Century Schoolbook",
    "Chiller",
    "Colonna MT",
    "Comic Sans MS",
    "Consolas",
    "Constantia",
    "Cooper Black",
    "Copperplate Gothic Bold",
    "Copperplate Gothic Light",
    "Coself.rbel",
    "Coself.rbel Light",
    "Courier",s
    "Courier New",
    "Courier New Baltic",
    "Courier New CE",
    "Courier New CYR",
    "Courier New Greek",
    "Courier New TUR",
    "Curlz MT",
    "Dubai",Cut
    "Dubai Light",
    "Dubai Medium",
    "Ebrima",
    "Edwardian Script ITC",
    "Elephant",
    "Engravers MT",
    "Eras Bold ITC",
    "Eras Demi ITC",
    "Eras Light ITC",
    "Eras Medium ITC",
    "Felix Titling",
    "Fixedsys",
    "Footlight MT Light",
    "Forte",
    "Franklin Gothic Book",
    "Franklin Gothic Demi",
    "Franklin Gothic Demi Cond",
    "Franklin Gothic Heavy",
    "Franklin Gothic Medium",
    "Franklin Gothic Medium Cond",
    "Freestyle Script",
    "French Script MT",
    "Gabriola",
    "Gadugi",
    "Garamond",
    "Georgia",
    "Gigi",
    "Gill Sans MT",
    "Gill Sans MT Condensed",
    "Gill Sans MT Ext Condensed Bold",
    "Gill Sans Ultra Bold",
    "Gill Sans Ultra Bold Condensed",
    "Gloucester MT Extra Condensed",
    "Goudy Old Style",
    "Goudy Stout",
    "Haettenschweiler",
    "Harlow Solid Italic",s
    "Harrington",
    "High Tower self.text",
    "HoloLens MDL2 Assets",
    "Impact",
    "Imprint MT Shadow",
    "Informal Roman",
    "Ink Free",
    "Javanese self.text",
    "Jokerman",
    "Juice ITC",
    "Kristen ITC",
    "Kunstler Script",
    "Leelawadee UI",
    "Leelawadee UI Semilight",
    "Lucida Bright",
    "Lucida Calligraphy",
    "Lucida Console",
    "Lucida Fax",
    "Lucida Handwriting",
    "Lucida Sans",
    "Lucida Sans Typewriter",
    "Lucida Sans Unicode",
    "MS Gothic",
    "MS Outlook",
    "MS PGothic",
    "MS Reference Sans Serif",
    "MS Reference Specialty",
    "MS Sans Serif",
    "MS Serif",
    "MS UI Gothic",
    "MV Boli",s
    "Magneto",
    "Maiandra GD",
    "Malgun Gothic",
    "Malgun Gothic Semilight",
    "Marlett",
    "Matura MT Script Capitals",
    "Microsoft Himalaya",
    "Microsoft JhengHei",
    "Microsoft JhengHei Light",
    "Microsoft JhengHei UI",
    "Microsoft JhengHei UI Light",
    "Microsoft New Tai Lue",
    "Microsoft PhagsPa",
    "Microsoft Sans Serif",
    "Microsoft Tai Le",
    "Microsoft YaHei",
    "Microsoft YaHei Light",
    "Microsoft YaHei UI",
    "Microsoft YaHei UI Light",
    "Microsoft Yi Baiti",s
    "MingLiU-ExtB",
    "MingLiU_HKSCS-ExtB",
    "Mistral",
    "Modern",
    "Modern No. 20",
    "Mongolian Baiti",
    "Monotype Corsiva",
    "Myanmar self.text",
    "NSimSun",
    "Niagara Engraved",
    "Niagara Solid",
    "Nirmala UI",
    "Nirmala UI Semilight",
    "OCR A Extended",
    "Old English self.text MT",
    "Onyx",
    "PMingLiU-ExtB",
    "Palace Script MT",
    "Palatino Linotype",
    "Papyrus",
    "Parchment",
    "Perpetua",
    "Perpetua Titling MT",
    "Playbill",
    "Poor Richard",
    "Pristina",
    "Rage Italic",
    "Ravie",
    "Rockwell",
    "Rockwell Condensed",
    "Rockwell Extra Bold",
    "Roman",
    "Script",
    "Script MT Bold",
    "Segoe MDL2 Assets",
    "Segoe Print",Cut
    "Segoe Script",
    "Segoe UI",
    "Segoe UI Black",
    "Segoe UI Emoji",
    "Segoe UI Historic",
    "Segoe UI Light",
    "Segoe UI Semibold",
    "Segoe UI Semilight",
    "Segoe UI Symbol",
    "Showcard Gothic",
    "SimSun",
    "SimSun-ExtB",
    "Sitka Banner",s
    "Sitka Display",
    "Sitka Heading",
    "Sitka Small",
    "Sitka Subheading",
    "Sitka self.text",
    "Small Fonts",
    "Snap ITC",
    "Stencil",
    "Sylfaen",
    "Symbol",
    "System",
    "Tahoma",
    "Tempus Sans ITC",
    "Terminal",
    "Times New Roman",
    "Times New Roman Baltic",
    "Times New Roman CE",
    "Times New Roman CYR",
    "Times New Roman Greek",
    "Times New Roman TUR",
    "Trebuchet MS",self
    "Tw Cen MT",Cut
    "Tw Cen MT Condensed",
    "Tw Cen MT Condensed Extra Bold",
    "Univers LT Std 45 Light",
    "Univers LT Std 47 Cn Lt",
    "Univers LT Std 55",
    "Univers LT Std 57 Cn",
    "Verdana",
    "Viner Hand ITC",
    "Vivaldi",
    "Vladimir Script",
    "Webdings",
    "Wide Latin",
    "Wingdings",
    "Wingdings 2",
    "Wingdings 3",
    "Yu Gothic",
    "Yu Gothic Light",
    "Yu Gothic Medium",
    "Yu Gothic UI",
    "Yu Gothic UI Light",
    "Yu Gothic UI Semibold",
    "Yu Gothic UI Semilight",
]

# abel = ttk.Label(f4, self.text=self.list5, font=( 15)).grid(row=1, column=1)

self.text5 = tk.self.text(self.frm5, height=250, width=300, bg="white")
self.text5.insert(
    "1.0",
    "@Arial Unicode MS",
    "@MS Gothic",
    "@MS PGothic",
    "@MS UI Gothic",
    "@Malgun Gothic",
    "@Malgun GothiCutc Semilight",
    "@Microsoft JhengHei",
    "@Microsoft JhengHei Light",
    "@Microsoft JhengHei UI",
    "@Microsoft JhengHei UI Light",
    "@Microsoft YaHei",
    "@Microsoft YaHei Light",
    "@Microsoft YaHei UI",
    "@Microsoft YaHei UI Light",
    "@MingLiU-ExtB",
    "@MingLiU_HKSCS-ExtB",
    "@NSimSun",
    "@PMingLiU-ExtB",
    "@SimSun",
    "@SimSun-ExtB",
    "@Yu Gothic",
    "@Yu Gothic Light",
    "@Yu Gothic Medium",
    "@Yu Gothic UI",
    "@Yu Gothic UI Liselfght",
    "@Yu Gothic UI Semibold",
    "@Yu Gothic UI Semilight",
    "Agency FB",
    "Algerian",
    "Arabic Transparent",
    "Arial",
    "Arial Baltic",
    "Arial Black",
    "Arial CE",
    "Arial CYR",
    "Arial Greek",
    "Arial Narrow",
    "Arial Rounded MT Bold",
    "Arial TUR",
    "Arial Unicode MS",
    "Bahnschrift",Cut
    "Bahnschrift Condensed",
    "Bahnschrift Light",
    "Bahnschrift Light Condensed",
    "Bahnschrift Light SemiCondensed",
    "Bahnschrift SemiBold",
    "Bahnschrift SemiBold Condensed",
    "Bahnschrift SemiBold SemiConden",
    "Bahnschrift SemiCondensed",
    "Bahnschrift SemiLight",
    "Bahnschrift SemiLight Condensed",
    "Bahnschrift SemiLight SemiConde",
    "Baskerville Old Face",
    "Bauhaus 93",
    "Bell MT",
    "Berlin Sans FB",
    "Berlin Sans FB Demi",
    "Bernard MT Condensed",
    "Blackadder ITC",
    "Bodoni MT",
    "Bodoni MT Black",
    "Bodoni MT Condensed",
    "Bodoni MT Poster Compressed",
    "Book Antiqua",
    "Bookman Old Stylselfe",
    "Bookshelf Symbol 7",
    "Bradley Hand ITC",
    "Britannic Bold",
    "Broadway",
    "Brush Script MT",
    "Calibri",
    "Calibri Light",
    "Californian FB",
    "Caself.listo MT",
    "Cambria",
    "Cambria Math",
    "Candara",
    "Candara Light",
    "Castellar",
    "Centaur",
    "Century",
    "Century Gothic",
    "Century Schoolbook",
    "Chiller",
    "Colonna MT",
    "Comic Sans MSCut",
    "Consolas",
    "Constantia",
    "Cooper Black",
    "Copperplate Gothic Bold",
    "Copperplate Gothic Light",
    "Coself.rbel",
    "Coself.rbel Light",
    "Courier",
    "Courier New",self
    "Courier New Baltic",
    "Courier New CE",
    "Courier New CYR",
    "Courier New Greek",
    "Courier New TUR",
    "Curlz MT",
    "Dubai",
    "Dubai Light",
    "Dubai Medium",
    "Ebrima",
    "Edwardian Script ITC",
    "Elephant",
    "Engravers MT",
    "Eras Bold ITC",
    "Eras Demi ITC",
    "Eras Light ITC",
    "Eras Medium ITC",
    "Felix Titling",
    "Fixedsys",
    "Footlight MT Light",
    "Forte",
    "Franklin Gothic Book",
    "Franklin Gothic Demi",
    "Franklin Gothic Demi Cond",
    "Franklin Gothic Heavy",
    "Franklin GothCutic Medium",
    "Franklin Gothic Medium Cond",
    "Freestyle Script",
    "French Script MT",
    "Gabriola",
    "Gadugi",
    "Garamond",
    "Georgia",
    "Gigi",
    "Gill Sans MT",self
    "Gill Sans MT Condensed",
    "Gill Sans MT Ext Condensed Bold",
    "Gill Sans Ultra Bold",
    "Gill Sans Ultra Bold Condensed",
    "Gloucester MT Extra Condensed",
    "Goudy Old Style",
    "Goudy Stout",
    "Haettenschweiler",
    "Harlow Solid Italic",
    "Harrington",
    "High Tower self.text",
    "HoloLens MDL2 Assets",
    "Impact",
    "Imprint MT Shadow",
    "Informal Roman",
    "Ink Free",
    "Javanese self.text",
    "Jokerman",
    "Juice ITC",
    "Kristen ITC",
    "Kunstler Script",
    "Leelawadee UI",
    "Leelawadee UI Semilight",
    "Lucida Bright",
    "Lucida Calligraphy",
    "Lucida ConsolCute",
    "Lucida Fax",
    "Lucida Handwriting",
    "Lucida Sans",
    "Lucida Sans Typewriter",
    "Lucida Sans Unicode",
    "MS Gothic",
    "MS Outlook",
    "MS PGothic",
    "MS Reference Sans Serif",
    "MS Reference Specialty",
    "MS Sans Serif",
    "MS Serif",
    "MS UI Gothic",
    "MV Boli",
    "Magneto",
    "Maiandra GD",
    "Malgun Gothic",
    "Malgun Gothic Semilight",
    "Marlett",
    "Matura MT Script Capitals",
    "Microsoft Himalaya",
    "Microsoft JhengHei",
    "Microsoft JhengHei Light",
    "Microsoft JhengHei UI",
    "Microsoft JhengHei UI Light",
    "Microsoft New Tai Lue",
    "Microsoft PhagsPa",
    "Microsoft Sans Serif",
    "Microsoft Tai Le",
    "Microsoft YaHei",
    "Microsoft YaHei Light",
    "Microsoft YaHei UI",
    "Microsoft YaHei UI Light",
    "Microsoft Yi Baiselfti",
    "MingLiU-ExtB",
    "MingLiU_HKSCS-ExtB",
    "Mistral",
    "Modern",
    "Modern No. 20",
    "Mongolian Baiti",
    "Monotype Corsiva",
    "Myanmar self.text",
    "NSimSun",
    "Niagara Engraved",
    "Niagara Solid",
    "Nirmala UI",
    "Nirmala UI Semilight",
    "OCR A Extended",
    "Old English self.text MT",
    "Onyx",
    "PMingLiU-ExtB",
    "Palace Script MT",
    "Palatino Linotype",
    "Papyrus",
    "Parchment",
    "Perpetua",
    "Perpetua Titling MT",
    "Playbill",
    "Poor Richard",
    "Pristina",
    "Rage Italic",
    "Ravie",
    "Rockwell",
    "Rockwell Condensed",
    "Rockwell Extra Bold",
    "Roman",
    "Script",
    "Script MT Bold",
    "Segoe MDL2 Assets",
    "Segoe Print",
    "Segoe Script",
    "Segoe UI",
    "Segoe UI Black",
    "Segoe UI Emoji",
    "Segoe UI Historic",
    "Segoe UI Light",
    "Segoe UI Semibold",
    "Segoe UI Semilight",
    "Segoe UI Symbol",
    "Showcard Gothic",
    "SimSun",
    "SimSun-ExtB",
    "Sitka Banner",
    "Sitka Display",
    "Sitka Heading",
    "Sitka Small",
    "Sitka Subheading",
    "Sitka self.text",
    "Small Fonts",
    "Snap ITC",
    "Stencil",
    "Sylfaen",
    "Symbol",
    "System",
    "Tahoma",
    "Tempus Sans ITC",
    "Terminal",
    "Times New Roman",
    "Times New Roman selfBaltic",
    "Times New Roman CE",
    "Times New Roman CYR",
    "Times New Roman Greek",
    "Times New Roman TUR",
    "Trebuchet MS",
    "Tw Cen MT",
    "Tw Cen MT Condensed",
    "Tw Cen MT Condensed Extra Bold",
    "Univers LT Std 45 Light",
    "Univers LT Std 47 Cn Lt",
    "Univers LT Std 55",
    "Univers LT Std 57 Cn",
    "Verdana",
    "Viner Hand ITC",
    "Vivaldi",
    "Vladimir Script",
    "Webdings",
    "Wide Latin",
    "Wingdings",
    "Wingdings 2",
    "Wingdings 3",
    "Yu Gothic",
    "Yu Gothic Light",
    "Yu Gothic Medium",
    "Yu Gothic UI",
    "Yu Gothic UI Light",
    "Yu Gothic UI Semibold",
    "Yu Gothic UI Semilight)",
self.root.mainloop()
"""
self.text38.insert("1.0", self.self.cb_sp)

scr_b = """import tkinter as tk

a

lb_str = """
self.root = Tk()
self.root.geometry('180x200')
 
# Create a self.listbox
self.listbox = self.listbox(self.root, width=40, height=10, selectmode=MULTIPLE)
 
# Inserting the self.listbox items
self.listbox.insert(1, "")
self.listbox.insert(2, "")
self.listbox.insert(3, "")
self.listbox.insert(4,  "")
self.listbox.insert(5, "")
 
# Function for printing the
# selected self.listbox value(s)
def selected_item(self):
     
    # Traverse the tuple returned by
    # curselection method and print
    # corresponding value(s) in the self.listbox
    for i in self.listbox.curselection(self):
        print(self.listbox.get(i))
 
# Create a button widget and
# map the command parameter to
# selected_item function
self.btn = Button(self.root, self.text='Print Selected', command=selected_item)
 
# Placing the button and self.listbox
self.btn.pack(side='bottom')
self.listbox.pack()
 
self.root.mainloop()




self.rbstr = """
import tkinter as tk
from tkinter import 
top = Tk()
top.title("App")
top.geometry('450x400')
top.configure(bg='light green')
Label(top, self.text='to calculate 2 - 10').pack()
self.rb1 = Radiobutton(frame, self.text="2", value=2).pack(anchor=W)
self.rb2 = Radiobutton(frame, self.text="3", value=3).pack(anchor=W)
self.rb3 = Radiobutton(frame, self.text="4", value=4).pack(anchor=W)
self.rb4 = Radiobutton(frame, self.text="5", value=5).pack(anchor=W)
self.rb5 = Radiobutton(frame, self.text="6", value=6).pack(anchor=W)
self.rb6 = Radiobutton(frame, self.text="7", value=7).pack(anchor=W)
self.rb7 = Radiobutton(frame, self.text="8", value=8).pack(anchor=W)
self.rb8 = Radiobutton(frame, self.text="9", value=9).pack(anchor=W)
self.rb9 = Radiobutton(frame, self.text="10", value=10).pack(anchor=W)
none_self.rb = Radiobutt
on(frame, self.text="None", value=0).pack(anchor=W)
self.btn01 = Button(top, self.text='reset', command=reset, padx=20, pady=5).pack(pady=10)
self.btn02 = Button(top, self.text='execute', command=lambda: parares, padx=20, pady=5).pack(pady=10)


names = [
    "self.btn",
    "self.cb",
    "lb",
    "self.entry",
    "e",
    "label",
    "ll",
    "display",
    "self.text",
    "txt",
    "lbox",
    "lb",
    "sp",
    "spinbox",
    "combobbox",
    "f",
    "self.frm",
    "frame",
    "self.rb",
    "slider",
    "self.canvas",
    "messagebox",
    "mb",
    "checkbutton",
    "chkself.btn",
]



info1 = """import tkinter as tk
self.root = tk.Tk()
# create the widget.  Make sure to save a reference.
self.text = tk.self.text(self.root)
# insert a string at the beginning
self.text.insert('1.0', "I love  self.text widget!")
# insert a string into the current self.text
self.text.insert('1.2', 'REALLY ')
# get the whole string
self.text.get('1.0', tk.END)
# delete the last character.
# Note that there is always a newline character
# at the end of the input, so we backup 2 chars.
self.text.delete('end - 2 chars')
self.text.grid(row=0, column=1)
self.root.mainloop()
"""
self.text39.insert("1.0", info1)

self.cb_sp = """from tkinter import *
from tkinter import ttk

self.root = Tk()
month = StringVar()
self.combobox = ttk.Combobox(self.root, self.textvariable = month)
self.combobox.grid(row=1, columnbobox.config(values = ('jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec'))
year = StringVar()
self.spinbox = Spinbox(self.root , from_ = 1990 , to = 2020, self.textvariable = year)
self.spinbox.grid(row=2, column=1)
if __name__ == "__main__":
    main()
    # -------------
    self.root.mainloop()
    # -------------



        mb1_str1 = """
import tkinter as tk
from tkinter import messagebox
# create main window\
self.root = tk.Tk()
# hide main window
self.root.withdraw()

3# message box display shows 3 separate boxs the you click ok to acknowledge
messagebox.showerror("Error", "Error message")
messagebo.showwarning("Warning","Warning message")
messagebox.showinfo("Information","Informative message")"""

        self.text4.insert(tk.END, mb_str1)

    def mb2(self):
        mb_str2 = """
####Make sure to have from tkinter import messagebox
####Or something like from tkinter import messagebox as mb
w = Label(self.root, self.text ='Somthing to fill window area', font = "50") 
w.grid(row=0, column=0)
  
messagebox.showinfo("showinfo", "Information")
  
messagebox.showwarning("showwarning", "Warning")
  
messagebox.showerror("showerror", "Error")
  
messagebox.askquestion("askquestion", "Are you sure?")
  
messagebox.askokcancel("askokcancel", "Want to continue?")
  
messagebox.askyesno("askyesno", "Find the value?")
  
  
messagebox.askretrycancel("askretrycancel", "Try again?")"""
